export { default as Navbar} from "./Navbar"
export { default as NavigationDots} from "./NavigationDots"
export { default as Socialmedia} from "./Socialmedia"
export { default as About} from "./About"
export { default as Contactcopy} from "./Contactcopy"
export { default as Skills} from "./Skills"
export { default as Footer} from "./Footer"