export { default as Navbar} from "./Navbar"
export { default as NavigationDots} from "./NavigationDots"
export { default as Socialmedia} from "./Socialmedia"
export { default as About} from "./About"
export { default as Aboutme} from "./Aboutme"
export { default as Works} from "./Works"
export { default as Contact} from "./Contact"
export { default as Footer} from "./Footer"